# Generated by Django 5.1.3 on 2025-08-29 20:09

import django.core.validators
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=140)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "image_cover",
                    models.ImageField(
                        null=True,
                        upload_to="img/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            ),
                            posts.models.validate_image_size,
                        ],
                    ),
                ),
            ],
        ),
    ]
